spring:
  config:
    activate:
      on-profile: mysql-dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: ${MYSQL_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  jwt:
    secret:
      access-secret-key: ${JWT_SECRET}
      refresh-secret-key: ${JWT_SECRET}
    token:
      access-expiration-time: ${JWT_ACCESS_EXPIRATION}
      refresh-expiration-time: ${JWT_REFRESH_EXPIRATION}
      issuer: ${JWT_ISSUER}

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            authorization-grant-type: authorization_code
            redirect-uri: ${KAKAO_REDIRECT_URI}
            scope:
              - profile_nickname
              - account_email
              - phone_number
            client-name: Kakao
            provider: kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
    aes:
      secret-key: ${AES_SECRET_KEY}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
    s3:
      private-bucket: ${AWS_S3_PRIVATE_BUCKET}
      public-bucket: ${AWS_S3_PUBLIC_BUCKET}
      public-base-url: ${AWS_S3_PUBLIC_BASE_URL}
      kms-key-id: ${AWS_KMS_KEY_ID}

pdf:
  font-path: fonts/NotoSansKR-Regular.ttf

contract:
  template-path: templates/contract-template.html

pre-signed-url:
  view-expiration-minutes: ${VIEW_EXPIRATION_MINUTES:10}
  download-expiration-minutes: ${DOWNLOAD_EXPIRATION_MINUTES:10}
  upload-expiration-minutes: ${UPLOAD_EXPIRATION_MINUTES:10}

external:
  nh:
    base-url: ${NH_BASE_URL}
    access-token: ${NH_ACCESS_TOKEN}
    iscd: ${NH_ISCD}
    fintech-apsno: ${NH_FINTECH_APSNO}
    api-svc-cd: ${NH_API_SVC_CD}
    api-svc-cd-received : ${NH_API_SVC_CD_RECEIVED}
    fin-acno: ${NH_FIN_ACNO}
    mangoboss-account: ${NH_MANGOBOSS_ACCOUNT}
    mangoboss-bankcode: ${NH_MANGOBOSS_BANKCODE}