spring:
  application:
    name: app

  profiles:
    default: ${SPRING_PROFILES_ACTIVE:dev}
    group:
      test: h2-test
      dev: mysql-dev
      prod: mysql-prod

  config:
    import: "application-dev.yml,application-test.yml"

server:
  port: 8080

test_env: ${TEST_ENV_VAR:test_is_fail}

external:
  business-api:
    key: ${BUSINESS_API_KEY:bussinessapikeytest}

logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.stat: INFO
    io.lettuce.core: INFO

sentry:
  dsn: ${SENTRY_DSN}
  send-default-pii: true
  auth:
    token: ${SENTRY_AUTH_TOKEN}