spring:
  config:
    activate:
      on-profile: mysql-dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: ${MYSQL_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  data:
    redis:
       host: ${REDIS_HOST:localhost}
       port: ${REDIS_PORT:6379}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  jwt:
    secret:
      access-secret-key: ${JWT_SECRET}
      refresh-secret-key: ${JWT_SECRET}
    token:
      access-expiration-time: ${JWT_ACCESS_EXPIRATION}
      refresh-expiration-time: ${JWT_REFRESH_EXPIRATION}
      issuer: ${JWT_ISSUER}

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            authorization-grant-type: authorization_code
            redirect-uri: ${KAKAO_REDIRECT_URI}
            scope:
              - profile_nickname
              - account_email
              - phone_number
            client-name: Kakao
            provider: kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id