spring:
  application:
    name: batch
  datasource:
    url: ${MYSQL_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: never
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.stat: DEBUG

server:
  port: 8081

external:
  nh:
    base-url: ${NH_BASE_URL}
    access-token: ${NH_ACCESS_TOKEN}
    iscd: ${NH_ISCD}
    fintech-apsno: ${NH_FINTECH_APSNO}
    api-svc-cd: ${NH_API_SVC_CD}
    api-svc-cd-received : ${NH_API_SVC_CD_RECEIVED}
    fin-acno: ${NH_FIN_ACNO}
    mangoboss-account: ${NH_MANGOBOSS_ACCOUNT}
    mangoboss-bankcode: ${NH_MANGOBOSS_BANKCODE}

cron:
  clock-out: ${CRON_CLOCK_OUT}
  payroll: ${CRON_PAYROLL}
  payslip: ${CRON_PAYSLIP}

transfer:
  max-retry: ${MAX_RETRY}
  payroll-batch-size: ${PAYROLL_BATCH_SIZE}
  payslip-batch-size: ${PAYSLIP_BATCH_SIZE}

pdf:
  font-paths: templates/fonts/NotoSansKR-Regular.ttf,templates/fonts/NotoSansKR-Bold.ttf

payslip:
  max-retry: ${MAX_RETRY:3}
  template-path: templates/payslip_template.html

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
    s3:
      private-bucket: ${AWS_S3_PRIVATE_BUCKET}
      kms-key-id: ${AWS_KMS_KEY_ID}