spring:
  application:
    name: batch
  datasource:
    url: ${MYSQL_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: never
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.stat: DEBUG

server:
  port: 8081

external:
  nh:
    base-url: ${NH_BASE_URL}
    access-token: ${NH_ACCESS_TOKEN}
    iscd: ${NH_ISCD}
    fintech-apsno: ${NH_FINTECH_APSNO}
    api-svc-cd: ${NH_API_SVC_CD}
    api-svc-cd-received : ${NH_API_SVC_CD_RECEIVED}
    fin-acno: ${NH_FIN_ACNO}
    mangoboss-account: ${NH_MANGOBOSS_ACCOUNT}
    mangoboss-bankcode: ${NH_MANGOBOSS_BANKCODE}