name: CD Pipeline

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:
    inputs:
      module:
        description: 'Select module to deploy'
        required: true
        default: 'app'
        type: choice
        options:
          - app
          - admin

jobs:
  deploy-app:
    if: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.module == 'app') || github.ref == 'refs/heads/dev' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build app module
        run: ./gradlew :app:clean :app:build
        env: 
          DB_URL: ${{ secrets.MYSQL_URL }}
          DB_USERNAME: ${{ secrets.MYSQL_USERNAME }}
          DB_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_ACCESS_EXPIRATION: ${{ secrets.JWT_ACCESS_EXPIRATION }}
          JWT_REFRESH_EXPIRATION: ${{ secrets.JWT_REFRESH_EXPIRATION }}
          JWT_ISSUER: ${{ secrets.JWT_ISSUER }}
          KAKAO_CLIENT_ID: ${{ secrets.KAKAO_CLIENT_ID }}
          KAKAO_REDIRECT_URI: ${{ secrets.KAKAO_REDIRECT_URI }}

      - name: Build app Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_NAME }}-app:latest ./app

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push app Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_NAME }}-app:latest

      - name: SSH and pull Docker image on EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.DEV_EC2_APP_HOST }}
          username: ${{ secrets.DEV_EC2_APP_USERNAME }}
          key: ${{ secrets.DEV_EC2_SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/workspace
            rm .env
            touch .env
            echo "PROJECT_NAME=${{ secrets.PROJECT_NAME }}" >> .env
            echo "MYSQL_DATABASE=${{ secrets.PROJECT_NAME }}" >> .env
            echo "MYSQL_USER=${{ secrets.MYSQL_USERNAME }}" >> .env
            echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
            echo "SPRING_DATASOURCE_URL=${{ secrets.MYSQL_URL }}" >> .env
            echo "SPRING_DATASOURCE_USERNAME=${{ secrets.MYSQL_USERNAME }}" >> .env
            echo "SPRING_DATASOURCE_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
            echo "TEST_ENV_VAR=${{ secrets.TEST_ENV_VAR }}" >> .env
            echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" >> .env
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
            echo "JWT_ACCESS_EXPIRATION=${{ secrets.JWT_ACCESS_EXPIRATION }}" >> .env
            echo "JWT_REFRESH_EXPIRATION=${{ secrets.JWT_REFRESH_EXPIRATION }}" >> .env
            echo "JWT_ISSUER=${{ secrets.JWT_ISSUER }}" >> .env
            echo "KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }}" >> .env
            echo "KAKAO_REDIRECT_URI=${{ secrets.KAKAO_REDIRECT_URI }}" >> .env
            echo "BUSINESS_API_KEY=${{ secrets.BUSINESS_API_KEY }}" >> .env
            echo "AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}" >> .env
            echo "AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}" >> .env
            echo "AWS_S3_CONTRACT_BUCKET=${{ secrets.AWS_S3_CONTRACT_BUCKET }}" >> .env
            echo "AWS_KMS_KEY_ID=${{ secrets.AWS_KMS_KEY_ID }}" >> .env
            echo "AES_SECRET_KEY=${{ secrets.AES_SECRET_KEY }}" >> .env
            echo "PDF_FONT_PATH=${{ secrets.PDF_FONT_PATH }}" >> .env
            echo "VIEW_EXPIRATION_MINUTES=${{ secrets.VIEW_EXPIRATION_MINUTES }}" >> .env
            echo "DOWNLOAD_EXPIRATION_MINUTES=${{ secrets.DOWNLOAD_EXPIRATION_MINUTES }}" >> .env
            echo "CONTRACT_TEMPLATE_PATH=${{ secrets.CONTRACT_TEMPLATE_PATH }}" >> .env
            
            echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
            docker compose down -v
            docker images -q ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_NAME }}-app:latest | grep -q . && docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_NAME }}-app:latest
            docker compose up -d

  deploy-batch:
    if: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.module == 'batch') || github.ref == 'refs/heads/dev' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build batch module
        run: ./gradlew :batch:clean :batch:build
        env:
          DB_URL: ${{ secrets.MYSQL_URL }}
          DB_USERNAME: ${{ secrets.MYSQL_BATCH_USERNAME }}
          DB_PASSWORD: ${{ secrets.MYSQL_BATCH_PASSWORD }}

      - name: Build batch Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_NAME }}-batch:latest ./batch

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push app Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_NAME }}-batch:latest

      - name: SSH and pull Docker image on EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.DEV_EC2_BATCH_HOST }}
          username: ${{ secrets.DEV_EC2_BATCH_USERNAME }}
          key: ${{ secrets.DEV_EC2_SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/workspace
            rm .env
            touch .env
            echo "PROJECT_NAME=${{ secrets.PROJECT_NAME }}" >> .env
            echo "MYSQL_DATABASE=${{ secrets.PROJECT_NAME }}" >> .env
            echo "MYSQL_USER=${{ secrets.MYSQL_BATCH_USERNAME }}" >> .env
            echo "MYSQL_PASSWORD=${{ secrets.MYSQL_BATCH_PASSWORD }}" >> .env
            echo "SPRING_DATASOURCE_URL=${{ secrets.MYSQL_URL }}" >> .env
            echo "SPRING_DATASOURCE_USERNAME=${{ secrets.MYSQL_BATCH_USERNAME }}" >> .env
            echo "SPRING_DATASOURCE_PASSWORD=${{ secrets.MYSQL_BATCH_PASSWORD }}" >> .env
            echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" >> .env
            echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
            docker compose down -v
            docker images -q ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_NAME }}-batch:latest | grep -q . && docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_NAME }}-batch:latest
            docker compose up -d

  deploy-admin:
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.module == 'admin' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build admin module
        run: ./gradlew :admin:clean :admin:build

      - name: Build admin Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}//${{ secrets.PROJECT_NAME }}-admin:latest ./admin

# TODO: admin api 만들고 설정 다시
#      - name: Log in to Docker Hub
#        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
#
#      - name: Push admin Docker image
#        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/admin:latest
#
#      - name: SSH and pull Docker image on EC2
#        uses: appleboy/ssh-action@v0.1.5
#        with:
#          host: ${{ secrets.EC2_ADMIN_HOST }}
#          username: ${{ secrets.EC2_ADMIN_USER }}
#          key: ${{ secrets.EC2_ADMIN_SSH_KEY }}
#          script: |
#            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
#            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/admin:latest
#            docker stop admin || true
#            docker rm admin || true
#            docker ps -q --filter "publish=8081" | xargs -r docker rm -f
#            docker run -d --name admin -p 8081:8081 ${{ secrets.DOCKERHUB_USERNAME }}/admin:latest
